// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OlMag.Manufacture2.Data;

#nullable disable

namespace OlMag.Manufacture2.Migrations
{
    [DbContext(typeof(SalesManagementContext))]
    [Migration("20250113085922_ContactPerson")]
    partial class ContactPerson
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("SalesManagement")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OlMag.Manufacture2.Models.Entities.SalesManager.ContactPersonEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DateArchived")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("ContactPersons", "SalesManagement");
                });

            modelBuilder.Entity("OlMag.Manufacture2.Models.Entities.SalesManager.CustomerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DateArchived")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Customers", "SalesManagement");
                });

            modelBuilder.Entity("OlMag.Manufacture2.Models.Entities.SalesManager.ContactPersonEntity", b =>
                {
                    b.HasOne("OlMag.Manufacture2.Models.Entities.SalesManager.CustomerEntity", "Customer")
                        .WithMany("ContactPersons")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("OlMag.Manufacture2.Models.Entities.SalesManager.ContactPersonInformationEntity", "Information", b1 =>
                        {
                            b1.Property<Guid>("ContactPersonEntityId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Email")
                                .HasColumnType("text");

                            b1.Property<string>("Note")
                                .HasColumnType("text");

                            b1.Property<string>("Phone")
                                .HasColumnType("text");

                            b1.Property<string>("Post")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("ContactPersonEntityId");

                            b1.ToTable("ContactPersons", "SalesManagement");

                            b1.ToJson("Information");

                            b1.WithOwner()
                                .HasForeignKey("ContactPersonEntityId");
                        });

                    b.Navigation("Customer");

                    b.Navigation("Information")
                        .IsRequired();
                });

            modelBuilder.Entity("OlMag.Manufacture2.Models.Entities.SalesManager.CustomerEntity", b =>
                {
                    b.OwnsOne("OlMag.Manufacture2.Models.Entities.SalesManager.CustomerInformationEntity", "Information", b1 =>
                        {
                            b1.Property<Guid>("CustomerEntityId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Email")
                                .HasColumnType("text");

                            b1.Property<string>("Note")
                                .HasColumnType("text");

                            b1.Property<string>("Phone")
                                .HasColumnType("text");

                            b1.HasKey("CustomerEntityId");

                            b1.ToTable("Customers", "SalesManagement");

                            b1.ToJson("Information");

                            b1.WithOwner()
                                .HasForeignKey("CustomerEntityId");
                        });

                    b.Navigation("Information")
                        .IsRequired();
                });

            modelBuilder.Entity("OlMag.Manufacture2.Models.Entities.SalesManager.CustomerEntity", b =>
                {
                    b.Navigation("ContactPersons");
                });
#pragma warning restore 612, 618
        }
    }
}
